version: '3.7'
services:
  elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION}
    image: ${IMAGE_PREFIX}elasticsearch:${ELASTIC_VERSION}
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: ${CONTAINER_PREFIX}elasticsearch
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - ./elasticsearch/data:/usr/share/elasticsearch/data:Z
      # - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      TZ: Asia/Shanghai
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # ES_JAVA_OPTS: -Xms2g -Xmx2g
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    # image: docker.elastic.co/logstash/logstash:${ELASTIC_VERSION}
    image: ${IMAGE_PREFIX}logstash:${ELASTIC_VERSION}
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: ${CONTAINER_PREFIX}logstash
    ports:
      - 5044:5044
      - 50000:50000/tcp
      - 50000:50000/udp
      - 9600:9600
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    depends_on:
      - elasticsearch
    environment:
      TZ: Asia/Shanghai
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      # LS_JAVA_OPTS: -Xms1g -Xmx1g
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    networks:
      - elk
    restart: unless-stopped

  kibana:
    # image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION}
    image: ${IMAGE_PREFIX}kibana:${ELASTIC_VERSION}
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    container_name: ${CONTAINER_PREFIX}kibana
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    environment:
      TZ: Asia/Shanghai
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      I18N_LOCALE: zh-CN
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    networks:
      - elk
    restart: unless-stopped

  setup:
    image: ${IMAGE_PREFIX}setup:${ELASTIC_VERSION}
    container_name: ${CONTAINER_PREFIX}setup
    profiles:
      - setup
    build:
      context: setup/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    init: true
    volumes:
      - ./setup/entrypoint.sh:/entrypoint.sh:ro,Z
      - ./setup/lib.sh:/lib.sh:ro,Z
      - ./setup/roles:/roles:ro,Z
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
      METRICBEAT_INTERNAL_PASSWORD: ${METRICBEAT_INTERNAL_PASSWORD:-}
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      HEARTBEAT_INTERNAL_PASSWORD: ${HEARTBEAT_INTERNAL_PASSWORD:-}
      MONITORING_INTERNAL_PASSWORD: ${MONITORING_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
    name: elk

# volumes:
#   elasticsearch:
#     name: es-volumes
