input {
    beats {
        port => 5044
    }

    tcp {
        port => 50000
    }

    # heartbeat {
    #     interval => 5
    #     message  => 'Hello from Logstash 💓'
    # }
}

## Add your filters / logstash plugins configuration here
filter {
    # mutate {
    #     remove_field => ["host"]
    #     remove_field => ["agent"]
    #     remove_field => ["event"]
    #     remove_field => ["@version"]
    #     remove_field => ["ecs"]
    #     remove_field => ["input"]
    #     remove_field => ["tags"]
    #     remove_field => ["[log][offset]"]
    #     remove_field => ["[log][flags]"]
    # }
    grok {
        # message已在filebeat用multiline插件合并为一行，Grok模式是单行匹配的
        match => { "message" => "\[%{TIMESTAMP_ISO8601:timestamp} %{WORD:log_level}\] \[in %{GREEDYDATA:source}:%{NUMBER:line_no}\]\n%{GREEDYDATA:content}" }
    }
    date {
        match => ["timestamp", "yyyy-MM-dd HH:mm:ss"]
        target => "@timestamp"
        locale => "zh-CN"
        timezone => "Asia/Shanghai"
    }
}

output {
    elasticsearch {
        hosts => 'elasticsearch:9200'
        user => 'logstash_internal'
        password => '${LOGSTASH_INTERNAL_PASSWORD}'
        # user => 'elastic'
        # password => 'changeme'
        index => "python-logs-%{+yyyy.MM.dd}"
    }
}
